### ISSUE TITLE
Feedback requested

### ISSUE THREAD

**Issue by sofer** [sofer/partnerships#1]
@iteles @nelsonic @izaakrogan @besarthoxhaj @rub1e. Feedback on this first draft appreciated.

**Comment by nelsonic** [comment]
Looks good. :+1:

**Comment by iteles** [comment]
This is a good start :+1: 

Only two things I would change in the immediate term (i.e. pre 2nd draft):
- I would firm up the wording here: https://github.com/sofer/partnerships#using-the-name (people shouldn't be using the name without our express permission full stop).
- I would suggest we rename the [Commercial](https://github.com/sofer/partnerships#commercial-work) section to Sustainability as this is the angle that the intended audience should be thinking about the 'agency' model of work.

Also, more generally, do you want all people who pick up the F&C model and start their own thing to be partners? Just to understand if 'partnerships' is the most descriptive name for this repo :+1:

**Comment by sofer** [comment]
@iteles this is super helpful. 

What I really want this document to be is a guide to people who approach us wanting help doing something similar. How do we engage with them? Do we try to be hard-nosed about it and extract maximum value from the interaction or do we try to be open-handed and encourage them to take the idea and run with it? 

Re-reading the document, maybe we should have something stronger along the lines of _"with organisations that share our values, we can offer a training and recruitment service to help you establish your school"_.

And are we missing a trick not offering some sort of franchise arrangement. So that in return for some sort of annual payment we agree to provide some sort of ongoing endorsement and support.

**Comment by rub1e** [comment]
A few things
- Some more context would be good. More specifics about who this is aimed at. What are the use cases? Has anyone requested this information? Who? Why would someone want to set up their own school? What will they get out of it? etc.
- I do think the franchise thing is a good angle - if someone in Sofia sees our materials and thinks "Great, I can use this for our learn-to-code club!" then more power to them. But anything more than that, anything where we have to devote time and resources, anything that affects us or our brand - all of that I want us getting something out of it - there is an opportunity cost to every email we answer.
  - So to your question of extracting value or letting them run with it, I'd say it depends on who they are and what they want to do  
- Isn't this basically the open source model anyway - use it for free with no support or pay us and we'll support you
- I'm not sure I like the idea of just offering up our personnel - it almost makes it feel like we're offering to do all the heavy lifting
- Resources - what about premises? And not just premises, but minimum two-tiered premises
- Materials - are our materials anywhere near the level they have to be for people to just pick them up and run with them? I feel like lots of work is needed before they are that usable - the material is there, but it's not organised or accessible, I'd say

**Comment by rub1e** [comment]
What about setting up an open-source FAC network? All coding schools or clubs dedicated to open-sourcing can join and use/contribute materials.

Nascent thought, but there's something there...

**Comment by sofer** [comment]
_"Isn't this basically the open source model anyway - use it for free with no support or pay us and we'll support you"_ @rub1e yes it is and it makes sense to use it as a starting point.

**Comment by sofer** [comment]
Comprehensive rewrite: https://github.com/sofer/partnerships/commit/262881efa3481cdbbed1e070ffca2316bd1ad238

**Comment by sofer** [comment]
Updated and merged.

**Comment by iteles** [comment]
@sofer Might be worth opening a separate issue for feedback on your new version?
